# Generated by Django 6.0.1 on 2026-01-27 18:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('data_retirada', models.DateField(default=django.utils.timezone.localdate)),
                ('destino', models.CharField(max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('PARCIAL', 'Parcial'), ('DEVOLVIDO', 'Devolvido')], default='ABERTO', max_length=12)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemTermo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio_num', models.CharField(max_length=50)),
                ('descricao_bem', models.CharField(max_length=255)),
                ('assinatura_retirada', models.CharField(blank=True, max_length=120)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('assinatura_devolucao', models.CharField(blank=True, max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='termos.termosaida')),
            ],
        ),
    ]
