# Generated by Django 6.0.1 on 2026-01-28 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termos', '0002_termosaida_responsavel_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemtermo',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='termosaida',
            options={'ordering': ['-criado_em']},
        ),
        migrations.RemoveField(
            model_name='itemtermo',
            name='assinatura_devolucao',
        ),
        migrations.RemoveField(
            model_name='itemtermo',
            name='assinatura_retirada',
        ),
        migrations.RemoveField(
            model_name='itemtermo',
            name='data_devolucao',
        ),
        migrations.AddField(
            model_name='itemtermo',
            name='observacao',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='itemtermo',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='termosaida',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemtermo',
            name='descricao_bem',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='itemtermo',
            name='patrimonio_num',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='termosaida',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='termosaida',
            name='data_retirada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='termosaida',
            name='responsavel_nome',
            field=models.CharField(blank=True, default='Não informado', max_length=120),
        ),
        migrations.AlterField(
            model_name='termosaida',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'ABERTO'), ('DEVOLVIDO', 'DEVOLVIDO'), ('CANCELADO', 'CANCELADO')], default='ABERTO', max_length=20),
        ),
    ]
