# Generated by Django 6.0.1 on 2026-01-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termos', '0003_alter_itemtermo_options_alter_termosaida_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termosaida',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='termosaida',
            name='numero',
        ),
        migrations.AddField(
            model_name='termosaida',
            name='patrimonio',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Patrimônio'),
        ),
        migrations.AddField(
            model_name='termosaida',
            name='produto',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='termosaida',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Devolução'),
        ),
        migrations.AlterField(
            model_name='termosaida',
            name='data_retirada',
            field=models.DateField(verbose_name='Data de Retirada'),
        ),
        migrations.AlterField(
            model_name='termosaida',
            name='destino',
            field=models.CharField(max_length=120, verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='termosaida',
            name='responsavel_nome',
            field=models.CharField(default='Não informado', max_length=120, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='termosaida',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'ABERTO'), ('DEVOLVIDO', 'DEVOLVIDO')], default='ABERTO', max_length=12, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='ItemTermo',
        ),
    ]
