# Generated by Django 6.0.1 on 2026-01-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termos', '0004_remove_termosaida_criado_por_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termosaida',
            old_name='responsavel_nome',
            new_name='responsavel',
        ),
        migrations.AddField(
            model_name='termosaida',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='termosaida',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='termosaida',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('DEVOLVIDO', 'Devolvido')], default='ABERTO', max_length=10, verbose_name='Status'),
        ),
    ]
