# Generated by Django 6.0.1 on 2026-02-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termos', '0005_rename_responsavel_nome_termosaida_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termosaida',
            options={'ordering': ['-data_retirada', '-id']},
        ),
        migrations.AlterField(
            model_name='termosaida',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='termosaida',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='termosaida',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='termosaida',
            name='data_retirada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='termosaida',
            name='destino',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='termosaida',
            name='patrimonio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='termosaida',
            name='produto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='termosaida',
            name='responsavel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='termosaida',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('DEVOLVIDO', 'Devolvido')], default='ABERTO', max_length=10),
        ),
    ]
