# Generated by Django 6.0.1 on 2026-02-10 16:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termos', '0006_alter_termosaida_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termosaida',
            name='atualizado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='termosaida',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='termosaida',
            name='destino',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='termosaida',
            name='produto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='termosaida',
            name='responsavel',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='termosaida',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'ABERTO'), ('DEVOLVIDO', 'DEVOLVIDO')], default='ABERTO', max_length=10),
        ),
    ]
